import { StoreType } from 'polotno/model/store';

export type Element = {
  set: (s: Record<string, any>) => void;
  alwaysOnTop: boolean;
  blurEnabled: boolean;
  blurRadius: number;
  borderColor: string;
  borderSize: number;
  brightness: number;
  brightnessEnabled: boolean;
  clipSrc: string;
  cornerRadius: number;
  cropHeight: number;
  cropWidth: number;
  cropX: number;
  cropY: number;
  custom: any;
  flipX: boolean;
  flipY: boolean;
  grayscaleEnabled: boolean;
  height: number;
  id: string;
  locked: boolean;
  opacity: number;
  rotation: number;
  selectable: boolean;
  sepiaEnabled: boolean;
  shadowBlur: number;
  shadowColor: string;
  shadowEnabled: boolean;
  shadowOffsetX: number;
  shadowOffsetY: number;
  showInExport: boolean;
  src: string;
  type: string;
  width: number;
  x: number;
  y: number;
};
